### ISSUE TITLE
Exclusions don't appear to be working

### ISSUE THREAD

**Issue by DigiAngel** [leunammejii/analsyt_arsenal#3]
Topic:

![screenshot from 2018-12-15 07-00-47](https://user-images.githubusercontent.com/947191/50043759-40b02e00-0037-11e9-8828-13d7edc34b8b.png)

Thank you!

**Comment by leunammejii** [comment]
Thanks for reporting this. The code was originally written to exclude the entire domain including the sub. I just pushed a update (v1.4.3) which should allow you exclude just the parent or even the TLD. Let me know if you run into any issues with the update.

![a](https://user-images.githubusercontent.com/12433311/50044288-5b8e9c80-004f-11e9-802a-bd00885c03a9.png)
